# Rcan news

## 1.3.72

* Improve warnings system
* Force csu_ageSpecific_top grup_by parameter to factor
* "year" accepted as variable name in csu_group_cases
* ICD grouping accepted other letters than C

## 1.3.71

* Update CI5 data to CI5XI data
* Fix calculation in age specific rate for population with less that 18 age group
* Fix error in hidden function affecting CanReg5 software
* Edit documentation
* Add warnings

## 1.3.70
* Add "csu_group_cases" function to group individual data into 5 years age-group data
* Add "csu_merge_cases_pop" function to merge registry data and population data
* Add "csu_bar_top" function to plot single-sided or double-sided top X bar chart 

## 1.3.64

* fix bug in graphics title

## 1.3.63

* Add option to select CI level for EAPC.
* Change default CI level from 90% to 95%.

## 1.3.62

* Add option to customize axis label in hidden function.

## 1.3.61

* Edit Title, description from CRAN submission.
* Remove unused hidden function. 

## 1.3.6

* add NEWS.RMD :)
* This is a new CRAN submission, so there is no news for this release.
