
# Rcan

Tools for basic and advance cancer statistics and graphics.

* Group individual data cases (by 5-years age group, ICD group, year, sex, ...)
* Merge registry data and population data. (by 5-years age group, year, sex, ...)
* Calculate Age-Standardized Rate (ASR), crude rate or Truncated Age-Standardized Rate (TASR) across different population (Registry, year, sex...).
* Calculate cumulative risk across different population (Registry, year, sex...).
* Calculate and plot Age-Specific Rate
* Calculate and plot Age-Specific Rate for the top X cancer or top X population
* Plot single-sided and double-sided  top X bar chart
* Plot cancer statistics over year.
* Calculate the Estimated Annual Percentage Change (EAPC) of rates during a time period with the Confidence Interval (CI) across different population (Registry, year, sex...).
* Plot cohort period age specific graph.

Rcan have been created at [the Cancer Surveillance Unit at International Agency for Research on Cancer](https://www.iarc.fr/en/research-groups/sec1/index.php) and 
is used by the software [CanReg5](http://www.iacr.com.fr/index.php?option=com_content&view=article&id=9:canreg5&catid=68&Itemid=445)



## Example

Here an example to calculate Age-standardized rate:

```{r example}
library(Rcan)
data(csu_registry_data_1)

# Age standardized rate (ASR) with no missing age cases.
result <- csu_asr(csu_registry_data_1, 
                  "age", "cases", "py",
                  group_by = c("registry", "registry_label" ),
                  var_age_group = c("registry_label"))
```
